#include<stdio.h>
#include<stdlib.h>
#include<time.h>

void main(){
    FILE *fp;
    int arr[50], i;
    system("rm Random.txt");
    fp = fopen("Random.txt", "a");
    fprintf(fp, "Sorted Random numbers Generated by 7_RandomSorted.c\n");
    srand(time(0));

    for(i =0; i<50; i++){
        arr[i] = (i==0)?rand()%100:arr[i-1]+rand()%100;
        fprintf(fp, "%d  ", arr[i]);
    }
    fclose(fp);
}